Name:           krust
Version:        0.1.0
Release:        1%{?dist}
Summary:        Krust application binary

License:        MIT OR Apache-2.0
URL:            https://github.com/bit-shift-io/krust
# Use the local archive generated by rpkg from the cloned repository
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  gcc

%description
Krust repository build managed by bit-shift-io.

%prep
%autosetup -p1
%cargo_prepir}/krust

%changelog
* Thu Aug 20 2026 Bronson Mathews <bronson@localhost> - 0.1.0-1
- Initial RPM package build for krust
